# Eat Safe, Love

## Notebook Set Up

In [1]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}

In [7]:
# Use count_documents to display the number of documents in the result
print("Number of documents in result:", establishments.count_documents(query))

Number of documents in result: 41

In [8]:
# Display the first document in the results using pprint
print("First result:")
results = establishments.find(query)
pprint(results[0])

First result:
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': '0',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64681b9339a784f34ce5fb80'),
 'geocode': {'latitude': '50.769705', 'longitude': '0.27694'},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [9]:
# Convert the result to a Pandas DataFrame
result_df = pd.DataFrame(results)
# Display the number of rows in the DataFrame
results_count = len(result_df)
results_count

41

In [10]:
# Display the first 10 rows of the DataFrame
result_df.head(10)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,64681b9339a784f34ce5fb80,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': '0.27694', 'latitude': '50.769705'}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
1,64681b9339a784f34ce5fef9,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': '1.278721', 'latitude': '51.8575...",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
2,64681b9339a784f34ce60203,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': '1.15927', 'latitude': '51.789429'}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
3,64681b9339a784f34ce603f7,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': '0.10202', 'latitude': '50.770885'}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
4,64681b9339a784f34ce60405,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': '0.101446', 'latitude': '50.7707...",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
5,64681b9339a784f34ce60da3,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': '0.736349', 'latitude': '51.5414...",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
6,64681b9339a784f34ce60fc5,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': '0.7121671', 'latitude': '51.535...",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
7,64681b9339a784f34ce62508,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': '0.602364', 'latitude': '51.5915...",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
8,64681b9339a784f34ce62935,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': '0.146449998021126', 'latitude':...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
9,64681b9339a784f34ce63149,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': '0.462307', 'latitude': '51.57005'}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [11]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {'RatingValue': {'$gte': '4'},
         'LocalAuthorityName': {'$regex': "London"}}
#query = {'LocalAuthorityName': {'$regex': "London"}}
# Use count_documents to display the number of documents in the result

# Display the first document in the results using pprint

In [12]:
# Use count_documents to display the number of documents in the result
print("Number of establishments in London:", establishments.count_documents(query))

Number of establishments in London: 34

In [13]:
# Display the first document in the results using pprint
print("First result:")
results = establishments.find(query)
pprint(results[0])

First result:
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': '4',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64681b9339a784f34ce61595'),
 'geocode': {'latitude': '51.369321', 'longitude': '0.508551'},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [14]:
# Convert the result to a Pandas DataFrame
london_df = pd.DataFrame(results)
# Display the number of rows in the DataFrame
pub_count = len(london_df)
pub_count

34

In [15]:
# Display the first 10 rows of the DataFrame
london_df.head(10)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,64681b9339a784f34ce61595,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,"{'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': '0.508551', 'latitude': '51.3693...",,4627.439468,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
1,64681b9339a784f34ce618be,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': '0.249255999922752', 'latitude':...",,4627.873179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
2,64681b9339a784f34ce6240a,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': '0.561954', 'latitude': '51.5438...",,4631.968418,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
3,64681b9339a784f34ce6320a,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': '0.346325', 'latitude': '51.4640...",,4636.847650,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
4,64681b9339a784f34ce6320b,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': '0.346336990594864', 'latitude':...",,4636.846754,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
5,64681b9339a784f34ce63915,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': '0.287555', 'latitude': '51.5040...",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
6,64681b9439a784f34ce65a1e,1252616,0,PI/000035653,Froottree,Other catering premises,7841,Tereza Joanne King George V Lock,Woolwich Manor Way London,Charlton,...,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': '0.0693250000476837', 'latitude'...",,4648.300000,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
7,64681b9439a784f34ce65a22,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': '0.069286', 'latitude': '51.5011...",,4648.301822,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
8,64681b9439a784f34ce65de9,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': '0.048006', 'latitude': '51.5037...",,4649.173485,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
9,64681b9439a784f34ce65dff,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': '0.047966', 'latitude': '51.5041...",,4649.188826,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None

### 3. What are the top 5 establishments with a `RatingValue` rating value of '5', sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [16]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

# "longitude":"0.08384000",
#         "latitude":"51.49014200"

# degree_search = 0.01
# latitude = 
# longitude = 

# query = 
query = {'geocode.longitude': {'$lt': "0.9384", '$gt': "0.7384"}, 
        'geocode.latitude': {'$lt': "51.500142", '$gt': "051.480142"}, 
         'RatingValue': "5"}
  

# Print the results
results = establishments.find(query)
pprint(results[0])

# sort = [('scores.Hygiene', 1)]

# # limit the results to the first 8
# limit = 5

# # Pretty print the results
# pprint(list(customers.find(query).sort(sort).limit(limit)))

{'AddressLine1': 'Dengemarsh Road',
 'AddressLine2': 'Lydd',
 'AddressLine3': 'Kent',
 'AddressLine4': '',
 'BusinessName': 'Lydd Town Football Club',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4596.449773016559,
 'FHRSID': 1495244,
 'LocalAuthorityBusinessID': 'PI/000078189',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'TN29 9JH',
 'RatingDate': '2022-06-15T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64681b9239a784f34ce5e726'),
 'geocode': {'latitude': '50.9322904559416', 'longitude': '0.912506450668238'},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1495244',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}

In [17]:
# sort = [('scores.Hygiene', 1)]

# # limit the results to the first 5
# limit = 5

# # # Pretty print the results
# #pprint(list(establishments.find(query).sort(sort).limit(limit)
# pprint(list(establishments.find(query).limit(limit)       
            
query = {}
sort = [('scores.Hygiene', 1)]

# Capture the results to a variable
results = establishments.find(query).sort(sort)

# Pretty print the first five results
for i in range(5):
    pprint(results[i])

{'AddressLine1': 'Folkestone Harbour',
 'AddressLine2': 'Harbour Approach Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': 'Little Rock',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4591.914705329384,
 'FHRSID': 1423242,
 'LocalAuthorityBusinessID': 'PI/000078141',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': '',
 'RatingDate': '2022-04-14T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64681b9239a784f34ce5e055'),
 'geocode': {'latitude': '51.0783519967076', 'longitude': '1.18590330311705'},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1423242',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': None,
            'Hygiene': None,
            'Structural': None}}
{'AddressLine1': 'Folkestone Harbour',
 'AddressLine2': 'Harbour Approach Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': 'Little Rock',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4591.914705329384,
 'FHRSID': 1423242,
 'LocalAuthorityBusinessID': 'PI/000078141',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': '',
 'RatingDate': '2022-04-14T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64681b9239a784f34ce5e055'),
 'geocode': {'latitude': '51.0783519967076', 'longitude': '1.18590330311705'},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1423242',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': None,
            'Hygiene': None,
            'Structural': None}}
{'AddressLine1': 'Folkestone Harbour',
 'AddressLine2': 'Harbour Approach Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': 'Little Rock',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4591.914705329384,
 'FHRSID': 1423242,
 'LocalAuthorityBusinessID': 'PI/000078141',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': '',
 'RatingDate': '2022-04-14T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64681b9239a784f34ce5e055'),
 'geocode': {'latitude': '51.0783519967076', 'longitude': '1.18590330311705'},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1423242',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': None,
            'Hygiene': None,
            'Structural': None}}
{'AddressLine1': 'Folkestone Harbour',
 'AddressLine2': 'Harbour Approach Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': 'Little Rock',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4591.914705329384,
 'FHRSID': 1423242,
 'LocalAuthorityBusinessID': 'PI/000078141',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': '',
 'RatingDate': '2022-04-14T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64681b9239a784f34ce5e055'),
 'geocode': {'latitude': '51.0783519967076', 'longitude': '1.18590330311705'},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1423242',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': None,
            'Hygiene': None,
            'Structural': None}}
{'AddressLine1': 'Folkestone Harbour',
 'AddressLine2': 'Harbour Approach Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': 'Little Rock',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4591.914705329384,
 'FHRSID': 1423242,
 'LocalAuthorityBusinessID': 'PI/000078141',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': '',
 'RatingDate': '2022-04-14T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('64681b9239a784f34ce5e055'),
 'geocode': {'latitude': '51.0783519967076', 'longitude': '1.18590330311705'},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1423242',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': None,
            'Hygiene': None,
            'Structural': None}}

In [18]:
# Convert result to Pandas DataFrame
Top5_df = pd.DataFrame(results)
Top5_df.head()

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,64681b9239a784f34ce5e055,1423242.0,0.0,PI/000078141,Little Rock,Other catering premises,7841,Folkestone Harbour,Harbour Approach Road,Folkestone,...,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': '1.18590330311705', 'latitude': ...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
1,64681b9239a784f34ce5e062,1058636.0,0.0,PI/000076450,Babaji,Takeaway/sandwich shop,7844,Folkestone Harbour,Harbour Approach Road,Folkestone,...,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': '1.18590330311705', 'latitude': ...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
2,64681b9239a784f34ce5e06e,1534966.0,0.0,PI/000080027,Putters!,Restaurant/Cafe/Canteen,1,Folkestone Harbour,Harbour Approach Road,Folkestone,...,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': '1.18590330311705', 'latitude': ...",,4591.914705,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
3,64681b9239a784f34ce5e072,1285095.0,0.0,PI/000077988,Folkestone Seasports,Retailers - other,4613,Shepway Sports Trust,The Stade,Folkestone,...,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': '1.18794649942731', 'latitude': ...",,4591.923505,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
4,64681b9239a784f34ce5e08b,511409.0,0.0,PI/000039931,The Lifeboat,Pub/bar/nightclub,7843,42 North Street,Folkestone,Kent,...,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': '1.186715', 'latitude': '51.0815...",,4592.005042,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [20]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match':{"scores.Hygiene": 0}}
# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': "$LocalAuthorityName", 
                          "Num_Docs": { '$sum': 1 }}}

# 3. Sorts the matches from highest to lowest
sort_query = {'$sort': {"Num_Docs": -1}}
# Print the number of documents in the result
pipeline = [match_query, group_query, sort_query]
results = list(establishments.aggregate(pipeline))

print("Number of classifications in result: ", len(results))

Number of classifications in result:  55

In [22]:
# Print the first 10 results
for i in range(10):
    pprint(results[i])

{'Num_Docs': 1130, '_id': 'Thanet'}
{'Num_Docs': 882, '_id': 'Greenwich'}
{'Num_Docs': 713, '_id': 'Maidstone'}
{'Num_Docs': 711, '_id': 'Newham'}
{'Num_Docs': 686, '_id': 'Swale'}
{'Num_Docs': 680, '_id': 'Chelmsford'}
{'Num_Docs': 672, '_id': 'Medway'}
{'Num_Docs': 607, '_id': 'Bexley'}
{'Num_Docs': 586, '_id': 'Southend-On-Sea'}
{'Num_Docs': 542, '_id': 'Tendring'}

In [23]:
# Convert the result to a Pandas DataFrame
hygiene_df = pd.DataFrame(results)
# Display the number of rows in the DataFrame
hyg_row_count = len(hygiene_df)
hyg_row_count

55

In [25]:
# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

               _id  Num_Docs
0           Thanet      1130
1        Greenwich       882
2        Maidstone       713
3           Newham       711
4            Swale       686
5       Chelmsford       680
6           Medway       672
7           Bexley       607
8  Southend-On-Sea       586
9         Tendring       542